### PR TITLE
Add additional details to CSV export (#5)

### LINKED ISSUE #5: CSV improvements
Could probably do this later today, but noticed a few more details should be present.
Should add: Number of premises, modified question details(negation, meta, analogies), and pts at time of question, to the data in the csv.

### PR DESCRIPTION
**Pull request by GiladKingsley**
Fixes #5

Added the following fields to the CSV export:
- Number of premises
- Question modifiers (negation, meta, analogies)
- Points at time of question

Changes made in:
- src/app/syllogimous/services/stats-export.service.ts

### CODE REVIEW

**Comment by 4skinSkywalker** [comment]
Why did you calculate the score that way? You have the score at the time of answering, it's just a matter of putting the score inside the questions

**Comment by GiladKingsley** [comment]
Ah, but now the 'User Score' column is empty on my phone's CSV download.

**Comment by 4skinSkywalker** [comment]
Because you have to play :) Old questions in your LS used the old model.

**Comment by GiladKingsley** [comment]
Oh I see, your implementation doesn't have backwards compatibility then?

**Comment by 4skinSkywalker** [comment]
Nope, you can derive points with calculations for sure but I won't trust it because tiers can change at any time (I mean that we could add or remove some of them making impossible to know how many points a user had in a given moment in the past)

**Comment by GiladKingsley** [comment]
Yeah I guess it's more robust

**Pull request merged**
